version: "3"
services:
  fhir:
    image: "hapiproject/hapi:v8.2.0-2"
    ports:
      - "8080:8080"
    environment:
      hapi.fhir.subscription.resthook_enabled: "true"
      hapi.fhir.subscription.websocket_enabled: "true"
      hapi.fhir.client_id_strategy: ANY
    volumes:
      - ./hapi.application.yaml:/config/hapi.application.yaml
    depends_on:
      - fhir-db
  fhir-db:
    image: postgres:17-alpine
    volumes:
      - fhir-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: 'hapi_r4'

volumes:
  fhir-db-data: